### PR TITLE
Fix copy_to with empty constraint rows

### LINKED ISSUE #172: Bug in copy_to
Using the file from https://discourse.julialang.org/t/highs-error-no-invertible-representation-for-getdualray/101372/11?u=odow
```julia
import HiGHS
import MathOptInterface as MOI
model = MOI.FileFormats.MOF.Model()
MOI.read_from_file(model, "/Users/Oscar/Downloads/test.mof.json")
MOI.set(model, MOI.ObjectiveSense(), MOI.FEASIBILITY_SENSE)
h = HiGHS.Optimizer()
MOI.copy_to(h, model)
julia> MOI.optimize!(h)
Presolving model
Presolve: Infeasible

Solving report
  Status            Infeasible
  Primal bound      inf
  Dual bound        -inf
  Gap               inf
  Solution status   -
  Timing            0.00 (total)
                    0.00 (presolve)
                    0.00 (postsolve)
  Nodes             0
  LP iterations     0 (total)
                    0 (strong br.)
                    0 (separation)
                    0 (heuristics)
ERROR:   No invertible representation for getDualRay
```
But the model is easy to grok that it should be feasible.

### PR DESCRIPTION
**Pull request by odow**
Closes #172 

This took me a while to find because...GLPK has the exact same bug. So I originally figured that two solvers meant the problem was in MOI.

### CODE REVIEW

File: test/MOI_wrapper.jl [hunk 1]
```diff
@@ -437,6 +437,28 @@ function test_attribute_TimeLimitSec()
...
+    F = MOI.ScalarAffineFunction{Float64}
+    c1 = MOI.add_constraint(model, 2.0 * x, MOI.GreaterThan(0.0))
+    c2 = MOI.add_constraint(model, zero(F), MOI.GreaterThan(0.0))
+    c3 = MOI.add_constraint(model, 1.0 * x, MOI.EqualTo(1.0))
+    h = HiGHS.Optimizer()
+    MOI.set(h, MOI.Silent(), true)
+    index_map = MOI.copy_to(h, model)
+    y = index_map[x]
+    @test MOI.get(h, MOI.ConstraintFunction(), index_map[c1]) ≈ 2.0 * y
+    @test MOI.get(h, MOI.ConstraintFunction(), index_map[c2]) ≈ g
```
Comment (odow) [inline test/MOI_wrapper.jl:452]:
```suggestion
    @test MOI.get(h, MOI.ConstraintFunction(), index_map[c2]) ≈ zero(F)
```

**Comment by odow** [comment]
The org-wide GitHub code search is quite useful:
image
