### PR TITLE
Fix SimplexIterations getter and add BarrierIterations

### LINKED ISSUE #86: SimplexIterations uses deprecated method
https://github.com/jump-dev/HiGHS.jl/blob/94ae3b566d807834b2f5521c4a4fbc4bb07c6b9a/src/MOI_wrapper.jl#L1792-L1794

should be replaced with lookups for 

https://github.com/ERGO-Code/HiGHS/blob/17237a320d5c32a95c18e1e8cf2ef4a365e9e889/src/lp_data/HighsInfo.h#L200-L205

### PR DESCRIPTION
**Pull request by odow**
Closes #86

### CODE REVIEW

File: test/MOI_wrapper.jl [hunk 1]
```diff
@@ -227,6 +227,45 @@ c8: w + x in MathOptInterface.Interval(1.0, 2.0)
...
+function _knapsack_model(; mip::Bool, solver::String)
+    model = HiGHS.Optimizer()
+    MOI.set(model, MOI.RawOptimizerAttribute("presolve"), "off")
+    MOI.set(model, MOI.RawOptimizerAttribute("solver"), solver)
+    N = 30
+    x = MOI.add_variables(model, N)
+    if mip
+        MOI.add_constraints(model, x, MOI.ZeroOne())
+    end
+    Random.seed!(1)
```
Comment (odow) [inline test/MOI_wrapper.jl:239]:
```suggestion
```

File: test/MOI_wrapper.jl [hunk 2]
```diff
@@ -227,6 +227,44 @@ c8: w + x in MathOptInterface.Interval(1.0, 2.0)
...
+    MOI.set(model, MOI.ObjectiveSense(), MOI.MAX_SENSE)
+    return model
+end
+
+function test_SimplexIterations_BarrierIterations()
+    model = _knapsack_model(mip = false, solver = "simplex")
+    @test MOI.get(model, MOI.SimplexIterations()) == 0
+    @test MOI.get(model, MOI.BarrierIterations()) == 0
+    MOI.optimize!(model)
+    @test MOI.get(model, MOI.SimplexIterations()) > 1
```
Comment (odow) [inline test/MOI_wrapper.jl:259]:
```suggestion
    @test MOI.get(model, MOI.SimplexIterations()) > 0
```
